amqp:
  admin:
    auto-created: true
  host: localhost
  port: 5672
  username: adm_videos
  password: 123456

mysql:
  username: ${DATABASE_MYSQL_USERNAME:root}
  password: ${DATABASE_MYSQL_PASSWORD:123456}
  schema: adm_videos
  url: ${DATABASE_MYSQL_URL:localhost:3306}

keycloak:
  realm: codeflix
  host: ${KEYCLOAK_HOST:http://localhost:8443}

server:
  port: 8080
  undertow:
    threads:
      worker: 10
      io: 2